language: java
env:
  global:
    - COMMIT_HASH=${TRAVIS_COMMIT::8}
before_script:
  - export BUILD_VERSION=`if [ "${TRAVIS_TAG}" == "" ]; then echo ${TRAVIS_BRANCH}-${COMMIT_HASH}; else echo ${TRAVIS_TAG} ; fi`
script: mvn clean package
deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "${TRAVIS_BUILD_DIR}/target/auctiongui-api-${BUILD_VERSION}.jar"
  skip_cleanup: true
  on:
    tags: true